Physics Year 2:
  subject: Physics
  name: Edexcel A level Physics ActiveBook 2
Pure Maths Year 1:
  subject: Mathematics
  name: Pure Mathematics Year 1
Pure Maths Year 2:
  subject: Mathematics
  name: Pure Mathematics Year 2
Applied Maths Year 1:
  subject: Mathematics
  name: Statistics and Mechanics Year 1
Applied Maths Year 2:
  subject: Mathematics
  name: Statistics and Mechanics Year 2
