textbooks: 
  Physics Year 2:
    subject:
    name:
  Pure Maths Year 1:
    subject:
    name:
  Pure Maths Year 2:
    subject:
    name:
  Applied Maths Year 1:
    subject:
    name:
  Applied Maths Year 2:
    subject:
    name:
